version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
  redis:
    image: redis:latest
  web:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile-debug
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app/app:/app
    restart: always
    depends_on:
      - db
      - redis
      - worker
    command: python main.py
  worker:
    build: ./fastapi_app
    restart: always
    depends_on:
      - redis
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./fastapi_app/app:/app
